services:
  servicio_get_data:
    build:
      context: ./get_data_microservice
      dockerfile: Dockerfile
    container_name: getDataContainer
    ports:
      - "5000:5000"
    environment:
      - USE_MOCK_DATA=1
    networks:
      - red_microservicios  # 👈 AÑADE ESTA LÍNEA

  

  servicio_process_data:
    build: ./Process_data_microservice
    container_name: processDataMicrosevice
    ports: 
      - "5001:5001"
    networks:
      - red_microservicios
    depends_on:
      - servicio_get_data

  
  servicio_kmeans:
    build: ./kmeans_service
    container_name: kmenasMicroservice
    ports: 
      - "5002:5002"
    networks:
      - red_microservicios
    depends_on:
      - servicio_process_data

  
  servicio_get_result:
    build: ./result_microservice
    container_name: getResultMicrosevice
    ports: 
      - "5003:5003"
    networks:
      - red_microservicios
    depends_on:
      - servicio_kmeans
  
  gateway:
    build: ./Gateway
    container_name: apiGateway
    ports:
      - "5050:5000"
    networks:
      - red_microservicios
    depends_on:
      - servicio_get_data
      - servicio_process_data
      - servicio_kmeans
      - servicio_get_result

  frontend:
    build: ./frontend
    container_name: frontendContainer
    ports:
      - "3000:80"
    networks:
      - red_microservicios
    depends_on:
      - gateway


networks:
  red_microservicios:
    driver: bridge
  